### ISSUE TITLE
Qtheads fails to configue on MacOS Ventura / M1

### ISSUE THREAD

**Issue by janciesko** [Qthreads/qthreads#129]
Qthreads fails to configure on MacOS Ventura and M1 hardware. 
Problem: configure detects the M1 as `arm`.
```
/usr/bin/uname -p = arm
/bin/uname -X     = unknown
/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
```

We do not have a the right switch in qthread_check_assembly.m4 for `arm`. The fallback to using ucontext fails also as Ventura fails to compile when including the `ucontext.h` (deprecated) header. 

```
In file included from conftest.c:80:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/ucontext.h:51:2: error: The deprecated ucontext routines require _XOPEN_SOURCE to be defined
```
Configure, compilation and tests succeed when above compilation error is avoided using ` CFLAGS=-D_XOPEN_SOURCE ./configure` when configuring.

**Comment by dmk42** [comment]
I believe this may be related to, or aggravated by, the fact that `QTHREAD_ARM` is not defined at the bottom of `include/qthread/common.h.in` where some of the other `QTHREAD_XXX` values are defined.  Consequently, tests like this
```c
# if (QTHREAD_ASSEMBLY_ARCH == QTHREAD_ARM)
```
are comparing against zero, which also matches `QTHREAD_UNSUPPORTED`.  In other words, whenever an error occurs that causes a supported target not to be found, the configuration code thinks it has found a 32-bit ARM.

It is possible that one or two other `QTHREAD_XXX` values are also not defined at the bottom of that file, so I would recommend a thorough search to find any of them that may be used anywhere in the code, and make sure they are all defined at the bottom of `include/qthread/common.h.in`.

I suspect that won't entirely fix this problem, but it will make it easier to debug at least.

**Comment by janciesko** [comment]
@dmk42 - thanks a lot for looking into that. It seems that the problem is gone. 
Reason: `autoconf` generates ./config/config.guess. When posting this issue, the timestamp variable in that script generated by autoconf was `timestamp='2018-05-05'`. After updating Ventura to 13.3.1(a), autoconf generates the file with `timestamp='2021-06-03'`. In other words, Ventura now ships with the updated autotools. The new script contains better arch recognition and 
```   
arm64:Darwin:*:*)
GUESS=aarch64-apple-darwin$UNAME_RELEASE
;;
```
Reconfiguring my directory as `autoreconf -fiv` with Ventura >=13.3.1(a) resolves the issue. 

RE: Missing / inconstant defines. Yes, that is an error and needs a fix.

**Comment by janciesko** [comment]
Follow-up https://github.com/Qthreads/qthreads/pull/134

**Comment by janciesko** [comment]
Marking as resolved.
